likeLion-FrontEnd-project/Hologram

css/login.css, pages/login.html
로그인 사용자 입력 폼 구현
resolves: #26
사용자 로그인 계정을 입력, 이메일 회원가입 페이지로 이동 기능 구현
- 이유
사용자 계정 정보를 받기 위한 폼 페이지 구현
- 작업 내역 
login.html 마크업 후 스타일 적용
- 동작 
이메일 회원가입 클릭 시 해당 페이지로 이동
- 특이 사항
close: #26
입력 시 레이아웃 변동 유무와 페이지 이동이 정상 동작하는지 확인 요망
=> [Add] login.html & login.css 파일 추가

css/join.css, pages/join.html
이메일로 회원가입 페이지 구현을 위한 파일 추가
resolves: #29
이메일 회원가입 페이지 구현
- 이유
이메일 회원가입을 통해 사용자 계정 생성
- 작업 내역 
- 동작 
input에 입력
- 특이 사항
close: #29
input에 입력 시 레이아웃 변동 유무 확인 요망
=> [Add] join.html & join.css 파일 추가

css/chat.css, pages/chat.html
채팅 페이지 header부분 마크업  구 변경과 아이콘 수정
resolves: #42
chat.html 아이콘 변경 & chat.css 아이콘 스타일 변경
- 이유
피그마 디자인과 동일하게 수정
- 작업 내역 
chat.html 아이콘 변경
chat.css 아이콘 스타일 변경
- 동작 
- 특이 사항
close: #42
=> [Update] chat.html & chat.css 아이콘 수정

css/tab-menu.css
resolves: #47 
- 하단 탭 메뉴 포커스 시 텍스트 색상 변경 필요
- 하단 탭 메뉴 포커스 시 텍스트 css 변경
- 없음
close: #47
=> [Update] 하단 tab-menu css 수정

css/chatroom.css, pages/chatroom.html
채팅방 페이지 아이콘 수정과 뒤로가기버튼 클릭시 채팅 페이지로 이동
resolves: #48
chatroom.html 아이콘 변경 & chatroom.css 아이콘 스타일 변경 및 채팅 페이지 연결
- 이유
피그마 스타일과 동일하게 적용
- 작업 내역 
chatroom.html 아이콘 변경
chatroom.css 아이콘 스타일 변경
chatroom 뒤로가기 버튼 클릭시 채팅 페이지로 이동
- 동작 
- 특이 사항
close: #48 
디자인 부분 확인
=> [Update] chatroom.html & chatroom.css 아이콘 수정 및 채팅 페이지 연결

assets/images/icon-arrow-left.svg, css/editprofile.css, pages/editprofile.html
프로필 수정 페이지 구현을 위한 파일과 이미지 파일 추가
resolves: #53
프로필 수정 페이지 구현
- 이유
프로필 수정 페이지 마크업 및 스타일 추가, 이미지 파일 추가
- 작업 내역 
- 동작 
사용자 입력 기능
- 특이 사항
close: #53 
레이아웃 변동 확인 요망
=> [Add] editprofile.html & editprofile.css 파일, 이미지 파일 추가

css/tab-menu.css
resolves: #58 
- 폴더구조 변경으로 이미지 경로와 이름 수정
- 이미지 경로와 이름 수정
close: #58
=> [Rename] tab-menu 경로와 이미지명 변경

assets/images/icon/icon-close.svg, css/chat.css, css/post.css, pages/chat.html, pages/chatroom.html, pages/post.html, pages/postcomment.html
post.html & postcomment.html & chat.html & chatroom.html 의 경로 및 이미지 변경
resolves: #60
post.html & postcomment.html & chat.html & chatroom.html 의 경로 및 이미지 변경
- 이유
폴더 구조 변경
- 작업 내역 
post.html 이미지 경로 변경
postcomment.html 이미지 경로 변경
chat.html 이미지 경로 변경
chatroom.html 이미지 경로 변경
- 동작 
- 특이 사항
close: #
=> [Rename] post.html & postcomment.html & chat.html & chatroom.html 경로 변경

css/product.css, pages/product.html
- 폴더 구조 변경으로 인한 경로 수정
- header 상단 고정을 위한 .nav 수정
- css와 이미지 경로 수정
- 동작 
- 특이 사항
close: #63
=> [Rename] product 페이지 html 경로, css 수정

css/search-init.css, pages/search-init.html
resolves: #67 
- 검색창 초기 화면 마크업, 스타일 추가
- 검색창 초기 화면 마크업, 스타일 추가
- 특이 사항 없음
close: #67
=> [Add] 검색창 초기 화면

css/modal.css, pages/modal-chat.html, pages/modal-comment-delete.html, pages/modal-comment-report.html, pages/modal-post.html, pages/modal-product.html, pages/modal-profile.html
resolves: #70 
- 모달창 html, css 추가
- 타입별 모달창 마크업
- 타입별 모달창 스타일
- 특이 사항 없음
close: #70 
- 혹시 누락된 내용 있는지 확인 부탁드립니다 😊
=> [Add] 모달창 html, css 추가

css/profile.css, pages/profile.html
- profile 페이지 html,css 수정 및 중복코드 제거
html - meta태그 내용 변경
css - 중복코드 제거
- 특이 사항
close: #79
=> [Update] profile 페이지 html,css 수정 및 중복코드 제거

css/followers.css, pages/followers.html
- 이유
- followes 페이지 html, css 추가
- 특이 사항
close: #45
=> [Add] followers 페이지 html, css

pages/chat.html
chat.html에 footer 추가
resolves: #83
- 이유
피그마와 동일하게 수정
- 작업 내역 
chat.html footer 추가
- 동작 
- 특이 사항
close: #83
=> [Update] chat.html footer 추가

css/post.css, pages/post.html
post.html 모달창 닫기 이미지에서 버튼으로 수정
resolves: #81
- 이유
자바스크립트 동작을 위해 버튼으로 수정
- 작업 내역 
post.html 모달창 닫기 버튼 생성
- 동작 
- 특이 사항
close: #81
=> [Update] post.html 모달창 수정

css/search-result.css, pages/search-result.html
resolves: #69 
- 검색창 결과 화면 html, css 추가
- 검색창 결과 화면 마크업
- 검색창 결과 화면 스타일
- 특이 사항 없음
close: #69
=> [Add] 검색창 결과 화면 html, css 추가

css/feed.css, pages/feed.html
resolves: #75
- 홈 피드 게시물 화면 html, css
- 홈 피드 게시물 화면 html
- 홈 피드 게시물 화면 css
- 나중에 사진 수정할게요!
- 특이 사항 없음
close: #75
- 카테고리별 게시글 화면 괜찮은지 확인 부탁드립니다 😊
-
=> [Add] 홈 피드 게시글 화면

css/modal.css
resolves: #99 
- 모달창 위치 변경
- 모달창 위치 css 파일 변경
- 특이 사항
close: #99
=> [Update] 모달창 css 변경

css/tab-menu.css, pages/feed.html, pages/home.html, pages/search-init.html, pages/search-result.html, pages/tab-menu.html
Resolves: #101 
- 중복 코드 제거 및 마크업과 스타일 수정
- 중복 코드 제거 
- 마크업과 스타일 수정 
- 페이지 이동 후에도 해당 페이지 탭 메뉴는 보라색으로 표시됨
- 해당되는 페이지 클래스에 clicked 를 추가해서 적용하시면 됩니다!
- 특이 사항 없음
close: #101
=> [Update] tab-menu html & css 수정

css/post.css, pages/post.html
post.html 이미지 링크 변경과 post.css 이미지 업로드 스타일 변경
resolves: #104 
- 이유
크롬에서 이미지를 읽어오지 못하여 이미지 링크 변경
이미지 업로드시 사진 크기 동일하게 맞춤
- 작업 내역 
post.html 이미지 링크 변경
post.css 이미지 업로드 스타일 변경
- 동작 
- 특이 사항
close: #104
=> [Update] post.html 이미지 링크 변경 & post.css 이미지 업로드 스타일 변경

css/profile.css, js/profile.js, pages/profile.html
- feed.html, css에서 피드 카드 내용 수정
- profile 페이지 게시글 리스트에 포스트 추가
feed.html, css에서 이미지 부분 div 추가 및 css 중복 수정
- ![image](https://user-images.githubusercontent.com/76831344/178634431-bab71216-c052-4353-998f-8676dbc7d356.png)
- 아이콘, 탭 메뉴는 해당 파일 머지하면 보일 예정
close: #96
=> [Update] profile.html,css 피드 추가 및 코드 수정

css/common.css, css/nav.css, html/nav.html
header html, css 통일/ common.css 추가
resolves: #112
header html, css 통일/ common.css 추가
- 이유
header UI 마크업 통일 / common.css 추가
header html, css 통일/ common.css 추가
- 작업 내역 
- 동작 
- 특이 사항
close: #112
=> [Update] header html, css 통일/ common.css 추가

css/nav.css, html/nav.html
누락된 공통 header UI(chat-nav) 추가
resolves: #128
누락된 공통 header UI(chat-nav) 마크업 및 스타일 추가
- 이유
공통 header UI(chat-nav) 누락
- 작업 내역 
chat.html 내 chat-nav 마크업 추가
nav.css 내 chat-nav 관련 스타일 추가
- 동작 
- 특이 사항
close: #128 
배치가 올바른지 확인
=> [Update] 누락된 공통 header UI(chat-nav) 추가

css/login.css, js/login.js, pages/login.html
login.html, login.css 수정 및 login.js 파일 추가
resolves: #118
login.html, login.css 파일 수정(마크업 수정 & 클래스 추가 및 수정)
- 이유
버튼 활성/비활성 상태 구현
로그인 시 페이지 이동 / 로컬 스토리지 토큰 저장
로그인 실패 시 에러 메세지 출력
- 작업 내역 
- 동작 
모든 input에 값을 입력 시 버튼 활성
올바르지 않은 값으로 로그인 시 에러 메세지 출력, 버튼 비활성
올바른 값으로 로그인 시 피드 페이지 이동
- 특이 사항
로컬스토리지 토큰 저장
close: #118 
버튼의 활성/비활성 상태 확인
로그인 성공 / 실패 시 동작
로컬스토리지 토큰 저장
=> [Add] login.html, login.css 수정 & login.js 파일 추가

css/editprofile.css, pages/editprofile.html
editprofile.html & editprofile.css 파일 수정
resolves: #121
editprofile.html & editprofile.css 파일 수정
- 이유
공통 header UI 통일
header UI 마크업 스타일 통일
- 작업 내역 
- 동작 
position: fixed로 상단 고정
조건 만족 시 버튼 동작
- 특이 사항
close: #121 
피그마 파일과 동일하게 했지만 margin-top 적당한지 확인
=> [Update] editprofile.html & editprofile.css 파일 수정

css/profile.css, pages/profile.html
profile.html, css 헤더, 피드 수정
resolves: #116
- 공통 ui 합치는 과정 중 수정
- profile.html, css 헤더, 피드 수정 
- 피드 최종 수정 후 다시 커밋할 예정
close: #116
=> [Update] profile.html, css 헤더, 피드, 탭메뉴 수정

css/search-result.css, pages/home.html, pages/search-init.html, pages/search-result.html
resolves : #123 
- nav 공통 html, css 적용 필요
- 각 파일 nav 부분 html, css 변경
- 특이 사항
close: #123
=> [Update] home,search html & css 코드 수정

js/login.js
login.js 로컬스토리지 "accountname"값 추가 등록
resolves: #137
로그인 시 로컬스토리지 "accountname"값 추가
- 이유
로그인 후 로컬스토리지 데이터를 사용하기 위함 
- 작업 내역 
로컬스토리지에 "accountname" 값을 추가하는 코드 추가
- 동작 
로컬스토리지에 데이터 추가 저장
- 특이 사항
close: #137 
로컬스토리지 "accountname" 데이터가 추가 확인
=> [Update] login.js 로컬스토리지 "accountname"값 추가 등록

css/post.css, js/post.js, pages/post.html
공통 ui를 위해 post.html 마크업 & post.css 스타일 수정
resolves: #131
- 이유
공통 ui로 통일
- 작업 내역 
post.html 마크업 공통 ui로 변경
post.css 스타일 수정
- 동작 
- 특이 사항
close: #131
=> [Update] post.html & post.css 변경

css/userList.css, html/userList.html
- 공통 ui 사용을 위한 추가
- 공통 ui인 검색 결과에서 유저 목록과 팔로워, 팔로잉에 보일 유저목록 구현 
- 
- 특이 사항
close: #126
=> [Add] 공통UI userList.html, css 구현

css/postcomment.css, pages/postcomment.html
공통 ui로 통일하기 위해 postcomment css 수정
resolves: #124
- 이유
공통 ui로 통일
- 작업 내역 
postcomment.html 공통 마크업 추가
postcomment.css 스타일 수정
- 동작 
- 특이 사항
close: #
=> [Update] postcomment.html & postcomment.css

css/chat.css, pages/chat.html
공통 ui를 위한 chat.html 마크업과 chat.css 스타일 수정
resolves: ##133
- 이유
공통 ui로 수정
- 작업 내역 
chat.html 마크업 수정
chat.css 스타일 수정
- 동작 
- 특이 사항
close: #133
=> [Update] chat.html & chat.css 변경

html/tab-menu.html, pages/home.html
resolves: #135 
- home.html 파일 수정 필요
- home.html 파일 nav와 footer 수정 
- 특이 사항
close: #135
=> [Update] home.html 파일 수정

css/feed.css, html/feed.html, html/modal-chat.html, html/modal-comment-delete.html, html/modal-comment-report.html, html/modal-post.html, html/modal-product.html, html/modal-profile.html, html/tab-menu.html
Resolves: #139 
- 공통 UI 파일 이동 & feed.css 변경 필요
- 공통 UI 파일 이동 & feed.css 변경
- 특이 사항
close: #139
=> [Update] 공통 UI 파일 이동 & feed.css 변경

css/imageRegister.css, html/imageRegister.html
공통 UI를 위해 이미지 업로드 버튼 html과 css 구현
resolves: #146
- 이유
공통 UI로 묶어주기 위함
- 작업 내역 
이미지 업로드 버튼 imageRegister.html 마크업과 imageRegister.css 스타일 구현
- 동작 
- 특이 사항
close: #146 
상품 등록 부분 backgroundcolor가 피그마에서 #c4c4c4라 #c4c4c4로 넣어줬는데 #c4c4c4 부분은 var(--light-gray-color) (#dbdbdb) 로 바꾸자고 했던 기억이 있어서 --light-gray-color로 할지 c4c4c4로 해야할지 모르겠습니당
=> [Add] 공통 UI imageRegister.html & imageRegister.css 구현

css/nav.css
- .title-nav영역이 main 영역과 구분되기 위해 z-index 및 속성들 추가
- .title-nav에 z-index및 속성들 추가로 스크롤이 올라가도 헤더영역이 고정되어있다.
- 특이 사항
close: #141
.title-nav를 적용한 페이지입니다. 헤더 확인 부탁드립니다.
=> [Update] nav.css에서 .title-nav 수정

css/userList.css, html/userList.html
- nav 길이에 맞춰 padding-top 수정
- 작업 내역 
- 현재 pr 확인중인 nav 머지되면 main 영역이 위로 올라가서 정상적으로 보일 예정
close: #148
=> [Update] 공통UI userList.css 수정

css/chatroom.css, pages/chatroom.html
공통 ui를 위한 chatroom.html 마크업과 chatroom.css 스타일 변경
resolves: #144
- 이유
공통 ui 로 변경
- 작업 내역 
chatroom.html 마크업  변경
chatroom.css 스타일 변경
- 동작 
- 특이 사항
close: #144
=> [Update] chatroom.html & chatroom.css 변경

css/postcomment.css, js/postcomment.js, pages/postcomment.html
댓글 생성 기능 추가
resolves: #158
- 이유
댓글 생성 기능 추가
- 작업 내역 
자바스크립트 댓글 생성 기능 추가
- 동작 
- 특이 사항
close: #158 
코드 깔끔하게 수정할 예정
일단 기능만 되도록 구현해썽요
=> [Add] postcomment.js 파일 추가

js/profile.js
- 이유
- 프로필 페이지에서 로그인한 사용자의 정보가 보여진다
- ![image](https://user-images.githubusercontent.com/76831344/179388451-ee2ba2c5-d201-4328-ae90-c9c0bd7cc529.png)
- 특이 사항
close: #153
커밋단위가 적당한지 확인부탁드립니다.
=> [Add] profile.js 로그인한 사용자 데이터 받아오기

css/input.css, html/input.html
공통 UI input.html & input.css 파일 추가
resolves: #156
input.html / input.css 파일 추가
- 이유
input을 협업 과정에서 동일한 마크업으로 통일하기 위함
input 마크업(로그인/회원가입/상품등록 input)
- 작업 내역 
- 동작 
input마다 다른 입력 타입 적용(url, number ...)
input 포커스 시 하단 바 컬러 변경
- 특이 사항
close: #156 
`<form>`태그 안 `<input>` 작성
`<form>`태그, `<div>`에 flex 적용
포커스 시 컬러 변경 확인
=> [Add] 공통 UI input.html & input.css 파일 추가

css/post.css
z-index사용해 모달창이 맨 앞으로 오게 변경
resolves: #151
- 이유
모달창이 header에 가려져서 z-index 사용함
- 작업 내역 
post.css 모달창 수정
- 동작 
- 특이 사항
close: #151
주석은 추후에 지울게요~!
=> [Update] post.css 모달창 수정

.vscode/settings.json, css/feed.css, html/feed.html, pages/profile.html
resolves : #162 
- 피드 html&css 변경 
-피드 html&css 변경 
- 
- 특이 사항
close: #162
=> [Update] 피드 html&css 변경

css/input.css, html/input.html
동일한 input UI 유지하기 위해 input.html 마크업 & input.css 스타일 수정
resolves: #168
에러 관련 마크업 & 스타일 추가
- 이유
동일한 UI 유지
input.html / input.css 마크업 스타일 추가
- 작업 내역 
- 동작 
포커스 시 `input` 하단 컬러 변경 
에러 시 `input` 하단 컬러 변경 및 에러 메세지 출력
- 특이 사항
close: #168
에러 시 동작 확인
=> [Update] input.html 마크업 & input.css 스타일 수정

css/post.css, js/post.js, pages/post.html
제목 : maxlength- 40 로 수정 , 내용 : maxlength -450로 수정 & 경로 수정
resolves: #165
- 이유
깔끔한 ui로 수정
업로드 시 프로필 페이지 이동
- 작업 내역 
제목 : maxlength- 40 로 수정 , 내용 : maxlength -450로 수정
업로드 시 프로필 페이지 이동
- 동작 
- 
- 특이 사항
close: #165
=> [Update] post.html & post.css 수정

css/input.css, html/input.html
동일한 UI 마크업 유지를 위한 input.html & input.css 마크업 스타일 수정
resolves: #170
input.html 마크업 및 input.css 스타일 변경(가운데 정렬, 에러 표시 등)
- 이유
공통 UI 마크업 스타일 유지
잘못된 type 변경하여 의미에 맞게 마크업
레이아웃 유지
- 작업 내역 
- 동작 
조건에 만족하지 않을 시 에러 표시 확인(gif 파일은 에러는 임시로 한 것이니 참고만 해주세요)
- 특이 사항
close: #170
에러 표시 확인
=> [Update] input.html & input.css 마크업 스타일 수정

css/login.css, js/login.js, pages/login.html
공통 UI 생성에 따라 login 파트 전체적으로 수정(html, css, js)
resolves: #174
login 파트 전체적으로 수정(html, css, js)
- 이유
공통 UI input 생성
- 작업 내역 
login.html 마크업 수정(input.html 생성으로 클래스명 변경)
login.css 스타일 수정(input.css 생성으로 중복 코드 발생한 부분 제거)
login.js 변수 수정, 로컬스토리지 코드 위치 수정
- 동작 
로그인 성공 시 로컬스토리지에 accountname과 token 저장
- 특이 사항
close: #174 
로컬스토리지에 저장이 정상적으로 되는지 확인
=> [Update] 공통 UI 생성에 따라 login 파트 전체적으로 수정(html, css, js)

js/postcomment.js
이전 게시물에 달았던 댓글 불러오기
resolves: #172
- 이유
댓글 불러오기 기능 추가
- 작업 내역 
postcomment.js 댓글 불러오기 기능 추가
- 동작 
- 특이 사항
close: #172
시간 부분은 따로 기능 만들 예정입니당
=> [Add] postcomment.js 댓글 불러오기 기능 추가

css/feed.css, css/modal.css, html/feed.html, js/feed.js, js/feedmodal.js, pages/home.html
resolves: #177 
- feed.js & modal.js 업로드
- html, css 수정
- feed.js & modal.js
- html, css 수정
- 게시글 시간, 좋아요, 댓글 기능은 아직 진행중입니다.
- 프로필 사진 클릭 시 프로필 탭으로 이동합니다.
close: #177 
- 각 게시글 간격이 적당한지
- 스크롤바 없애는게 나을까요? 
- 이미지가 흰색이거나 없을 경우에 배경이랑 잘 구분이 안되는데, 배경색 없어도 괜찮을까요?
=> [Add] feed.js, modal.js 업로드 & html, css 파일 수정

css/join.css, js/join.js, pages/join.html
join 회원가입 기능 추가
resolves: #183
회원가입 기능 추가
- 이유
- 작업 내역 
join.html 마크업
join.css 스타일 추가
join.js 파일 추가
- 동작 
회원가입 성공 시 로그인 페이지 이동
로그인 성공 시 내 정보 페이지에 회원가입 데이터가 반영
- 특이 사항
close: #183 
회원가입 기능 확인 필요
내 정보 페이지에 데이터가 반영되는지 확인 필요
=> [Add] join 회원가입 기능 추가

css/postcomment.css, js/postcomment.js, pages/postcomment.html
댓글 신고 기능 & 댓글 삭제 기능
resolves: #181
- 이유
댓글 신고 기능과 댓글 삭제 기능 추가
댓글 신고 기능 & 댓글 삭제 기능
- 작업 내역 
- 동작 
* 신고 버튼 클릭
* 취소 버튼 클릭 
-----
* 삭제 버튼 클릭 시
- 특이 사항
close: #181 
동작 잘 작동하는지 확인
=> [Add] postcomment.js 기능 추가

css/feed.css, js/feedDetail.js, js/home.js, pages/feedDetail.html, pages/home.html
resolves: #186 
- home.js & feedDetail 파일 추가
- feed.css 페이지마다 적용되는 스타일 달라 변경함
- 작업 내역 
- 특이 사항
close: #186
=> [Add] home & feedDetail 추가 및 css 수정

js/search.js, pages/search-result.html
resolves: #190 
- 검색창 js 파일 추가
- js 에 따라 html 코드 수정
- 검색창 js 파일 추가
- 검색어 입력시 계정 결과 불러옴
- 프로필 클릭 시 해당 페이지로 이동
- 동작 
- 일부 이미지를 불러오지 못하는 에러가 있어서 해결 예정입니다
close: #190
=> [Add] 검색창 js 파일 추가

css/followings.css, css/userList.css, html/userList.html, js/followings.js, pages/followings.html
- 사용자가 팔로잉 중인 사용자 목록 구현
ui 변경에 따른 userList 수정
- 작업 내역 
-  ![image](https://user-images.githubusercontent.com/76831344/179900779-f42722b8-13f6-40c3-abce-e6491741e901.png)
- ![image](https://user-images.githubusercontent.com/76831344/179900707-da0edbb5-124e-4e41-a96c-5c23aff488e6.png)
- 팔로우 한 유저가 없을 경우
- 특이 사항
close: #164
=> [Add] following 목록 생성, userList 수정

css/profile.css, js/profile.js, pages/profile.html
- 프로필 페이지 nav의 설정 및 로그아웃 모달 추가
- nav의 메뉴버튼 선택 시 설정 및 로그아웃 모달이 보인다.
로그아웃을 선택하면 로그아웃 모달이 보인다.
- 
- 특이 사항
close: #193
=> [Add] profile 페이지 nav 모달 추가 

css/postcomment.css, js/postcomment.js, pages/postcomment.html
postcomment.js 게시글 불러오기 기능 & 신고 기능 추가
resolves: #201
- 이유
댓글 클릭 시 해당 게시글 불러오는 기능 추가 & 게시물 클릭 시 신고 기능 추가
- 작업 내역 
postcomment.js 게시글 불러오기 기능 추가
postcomment.js 게시글 신고하기 기능 추가
- 동작 
- 특이 사항
close: #201
위정님이랑 합쳐봐야하는 부분이라서 기능 작동하면 주석 지울 예정
=> [Add] postcomment.js 기능 추가 

css/feed.css, css/modal.css, css/search-result.css, js/feed.js, js/feedDetail.js, js/home.js, js/search.js, pages/home.html, pages/search-result.html
Resolves : #196 
- 홈, 검색창 ui & js 수정 필요
- 게시글 영역 너비 조정
- 페이지 이동 시 탭 색상 변경
- 게시글 댓글 아이콘 클릭시 댓글창으로 연결
- 검색창 전체화면일 때 검색결과는 화면 가운데 정렬
- 검색 결과 프로필 계정 옆에 팔로우, 취소 버튼 추가
- 계정 검색시 팔로우 버튼 텍스트 크기는 기능 추가 후 변경 예정입니다!
close: #196
=> [Update] 홈, 검색창 ui & js 수정

css/profile.css, js/profile.js, pages/profile.html
- 이유
- 작업 내역 
- 동작 
- 파일 충돌로 인해 다시 pr했습니다. 바로 머지하겠습니다. 
close: #204
=> [Add] 프로필 페이지 팔로우 버튼 기능

js/home.js, js/post.js, js/postcomment.js
경로 변경
resolves: #211
- 이유
- 작업 내역 
- 동작 
- 특이 사항
close: #
=> [Update] 경로 변경

js/profile.js, pages/profile.html
profile.js 에러 발생 시 에러 페이지 이동
resolves: ##220
- 이유
profile.js 에러 발생 시 에러 페이지 이동
- 작업 내역 
profile.js 에러 발생 시 에러 페이지 이동
- 동작 
- 특이 사항
close: #220
=> [Update] profile.js 수정

css/product.css, js/product.js, pages/product.html
- product 페이지 이미지 등록, 상품명, 상품가격 유효성 검사
- product 페이지 이미지 등록
- 상품명 글자 수 제한 검사, 에러메세지 출력
- 상품가격 숫자만 입력, 원 단위 콤마 추가
- ![image](https://user-images.githubusercontent.com/76831344/180341624-39ce83f2-e1b7-4888-9538-f5f1efd3ca22.png)
- 이미지 처리하던 중 '이미지 등록' 글자 추가를 못했습니다. 현우님이 작업하실 때 추가해달라고 전달했습니다.
close: #185
=> [Add] product 페이지 이미지 등록, 상품명, 상품가격 유효성 검사

js/home.js, js/search.js, pages/home.html
resolves: #216 
- 좋아요 기능 추가
- 좋아요 버튼 클릭시 카운팅 기능 추가
- 동작 
- 버튼 클릭시 아이콘 색만 변경되고 숫자는 그대로
- 새로고침해야 숫자가 카운팅 되지만 아이콘 색은 초기화 됨
close: #216
=> [Add] home.js 좋아요 기능 추가

js/home.js, js/profile-post.js, pages/profile.html
resolves: #225 
- profile-post.js 파일 추가 필요
- 프로필 탭 클릭시 현재 로그인 된 내 계정 프로필로 이동
- 내 계정 프로필 & 게시글 보여줌
- 특이 사항
close: #225
=> [Add] profile-post.js 파일 업로드

css/nav.css, js/product.js, pages/product.html
product.js 기능 추가(입력값과 에러 상태에 따른 버튼 상태 / 상품 등록)
공통 UI nav.css 수정
resolves: #223
입력값과 에러 상태에 따른 버튼 상태 / 상품 등록
버튼 비활성 시 클릭불가 포인터로 변경, 활성 시 클릭가능 포인터로 변경
- 이유
필수 데이터를 얻어서 프로필로 전달하기 위함
버튼 비활성 시 클릭가능 포인터를 띄우는 것은 사용자 경험에 좋지 않을 것 같다는 판단
- 작업 내역 
- 동작 
상품 등록 성공 시 위처럼 콘솔에 출력(확인용) - 위의 gif 이미지와 다른 상품 등록
- 특이 사항
링크는 404.html로 설정했음
close: #223 
프로필에 정상적으로 출력이 되는지 확인(다빈님 작업중)
=> [Add] product.js 기능 추가(입력값과 에러 상태에 따른 버튼 상태 / 상품 등록) 및 공통 UI nav.css 수정

css/chatroom.css, css/modal.css, css/postcomment.css, js/backchat.js, js/common.js, js/post.js, js/postcomment.js, pages/chat.html, pages/chatroom.html, pages/postcomment.html
게시글 댓글 페이지 로그아웃 & 채팅 페이지 로그아웃 & 개인프로필 로그아웃 & 채팅방 페이지 나가기
resolves: #227 
- 이유
로그아웃 & 채팅방 나가기 기능 추가
- 작업 내역 
게시글 댓글 페이지 로그아웃 & 채팅 페이지 로그아웃 & 개인프로필 로그아웃 & 채팅방 페이지 나가기
- 동작 
- 특이 사항
close: #227
=> [Add] 로그아웃 기능 & 채팅방 나가기 기능추가

pages/404.html
404 페이지 기능 구현(이전 페이지로 이동 버튼)
resolves: #229
이전 페이지 이동 버튼 구현
- 이유
- 작업 내역 
- 해당 이미지에서 보이는 페이지는 임시 테스트 파일로 실제 디렉토리에는 존재하지 않음
- 동작 
버튼 클릭 시 이전 페이지로 돌아간다. 
- 특이 사항
별도의 스크립트 없이 인라인으로 적용
close: #229 
버튼 동작 확인
=> [Add] 404 페이지 기능 구현(이전 페이지로 이동 버튼)

js/backchat.js
채팅방 뒤로가기 기능 추가
resolves: #232
- 이유
- 작업 내역 
- 동작 
- 특이 사항
close: #
=> [Add] 채팅방 뒤로가기 기능 추가

css/profile.css, js/profile-product.js, js/profile.js, pages/profile.html
- 프로필 페이지에서 등록한 판매상품의 데이터를 보여주고 모달로 수정, 삭제로 넘어갈 수 있게 한다.
- 판매 상품이 있을 경우 해당 영역을 보여준다.
- 판매 상품이 없을 경우 해당 영역을 가린다.
- 판매중인 상품을 선택하면 수정, 삭제 모달이 보여진다.
- ![image](https://user-images.githubusercontent.com/76831344/180415271-e4f5edda-ea1c-4d92-8dd0-8a8dc69e92b6.png)
- 다른사람의 상품 선택 시 모달은 아직 미완성
close: #221
=> [Add] profile 페이지 판매 상품 탭 데이터 처리, 모달

css/profile.css, js/editProduct.js, js/profile-product.js, js/profile.js, pages/editProduct.html, pages/profile.html
- 판매중인 상품의 수정과 삭제
- 다른 유저가 판매중인 상품의 이미지와 상품명을 전부 확인하기 위한 모달
- 프로필페이지에서 상품 수정 선택 시 editProduct에서 상품 수정
- 프로필 페이지에서 상품 삭제
- 다른유저의 상품인 경우 상품 확인 모달
- 나의 상품일 경우
- 상품 수정
- 상품 삭제
- 다른 유저의 상품일 경우
- profile.html, css, js를 전부 수정했습니다.
close: #242
1. 예외처리 놓친 부분 확인 부탁드립니다.
2. 상품 확인 모달창에서 이미지 크기별로 모달창의 height이 달라지는데 보기에 괜찮은가요?
=> [Add] profile 페이지 상품 수정, 삭제, 확인 모달

css/feed.css, html/feed.html, js/home.js, js/like.js, js/postcomment.js, js/profile-post.js
resolves: #240 
- 좋아요 클릭 시 실시간으로 반영되지 않는 부분 변경 필요
- 홈 피드, 댓글 페이지, 프로필 페이지에서 좋아요 클릭 시 카운팅 실시간 반영 및 새로고침 해도 하트 유지 
- 특이 사항
close: #240 
- 작업 내역에 있는 내용과 동일하게 작동하는지 체크 부탁드립니다 ~!
=> [Update] 홈 피드, 프로필페이지, 댓글페이지 좋아요 기능 수정

css/modal.css, js/editpost.js, js/postcomment.js, js/profile-post.js, pages/editpost.html, pages/profile.html
게시글 수정 기능 , 삭제 기능, 신고 기능 & 댓글 프로필 클릭 시 프로필 페이지 이동
resolves: #248
- 이유
게시글 수정 기능 , 삭제 기능, 신고 기능 & 댓글 프로필 클릭 시 프로필 페이지 이동
- 작업 내역 
게시글 수정 기능 , 삭제 기능, 신고 기능 & 댓글 프로필 클릭 시 프로필 페이지 이동
- 동작 
- 특이 사항
close: #248
머지 후 동작 체크
=> [Add] 게시글 수정 ,삭제, 신고 기능 추가 & 댓글 프로필 클릭 시 프로필 페이지 이동

js/postcomment.js, js/profile-post.js, js/profile.js, pages/profile.html
resolves: #244 
- 프로필 페이지에서 앨범뷰 버튼 클릭 시 전환 기능 필요
-  프로필 페이지에서 앨범뷰 버튼 클릭 시 전환 기능
close: #244
=> [Add] 프로필 페이지 앨범뷰 전환 기능 추가

js/profile.js
resolves: #245
- 이유
- 해당 유저가 작성한 게시글이 없을 경우 해당 영역을 가리고
작성한 게시글이 있을 경우 보여준다
- 
- 특이 사항
close: #245
=> [Add] profile 페이지 게시글 영역 조건부 렌더링

css/feed.css, css/profile.css, js/editProduct.js, js/product.js, js/profile.js
- 상품 등록 중 이미지가 보이고 전송되지만 데이터가 넘어가지 않는다.
- 상품 이미지 용량이 클 경우 alert로 사용자에게 이미지 용량이 크다고 알려준다.
- 
- 특이 사항
close: #252
=> [Fix] 상품 등록, 수정 이미지 용량 경고 처리

css/chatroom.css, css/post.css, css/postcomment.css, js/chatroom.js, js/editpost.js, js/post.js, js/postcomment.js, pages/chatroom.html
게시물 수정 클릭 시 원래 게시물 받아오기 & 댓글 작성 부분 프로필 이미지 변경 & 댓글 작성 에러 처리 & 채팅방 채팅 시 버튼 on & 카테고리 - 게시글 선택하기 제외시키기
resolves: #261
- 이유
에러 처리
- 작업 내역 
1. 게시물 수정 클릭 시 원래 게시물 받아오기 
2. 댓글 작성 부분 프로필 이미지 변경
3. 댓글 작성 에러 처리
4. 채팅방 채팅 시 버튼 on
5. 카테고리 - 게시글 선택하기 제외시키기
1. 게시물 수정 클릭 시 원래 게시물 받아오기
2. 댓글 작성 부분 프로필 이미지 변경 3. 댓글 작성 에러 처리
4. 채팅방 채팅 시 버튼 on
5. 카테고리 - 게시글 선택하기 제외시키기
- 동작 
- 특이 사항
close: #261
=> [Update] 게시물 수정 클릭 시 원래 게시물 받아오기 / 댓글 작성 부분 프로필 이미지 변경 & 댓글 작성 에러 처리 / 채팅방 채팅 시 버튼 on /  게시글 선택하기 제외시키기 기능 추가

css/feed.css, js/home.js
resolves: #264 
- 좋아요 댓글 UI 글자겹침 현상 수정
- feed.css 파일 수정
- 특이 사항
close: #264
=> [Update] 좋아요, 댓글 UI 겹침 현상 수정

css/postcomment.css
글자 넘침 수정
resolves: #266
- 이유
글자 넘침 
- 작업 내역 
postcomment  에 word-break: break-word;  추가
- 동작 
- 특이 사항
close: #266
=> [Fix] postcomment 글자 넘침 수정

css/postcomment.css
이미지 눌림 해결
resolves: #269
- 이유
이미지 눌림
- 작업 내역 
object-fit: cover; 추가
- 동작 
- 특이 사항
close: #269
=> [Update] 이미지 눌림 현상 해결

js/splash.js, pages/editprofile.html, pages/join.html
회원가입 / 프로필 수정 페이지 글자수 제한 추가 및 splash 경로 변경
resolves: #268
회원가입 / 프로필 수정 페이지 글자수 제한 추가
splash 경로 변경
- 이유
회원가입 / 프로필 수정 페이지 글자수 제한 추가
splash 경로 변경
- 작업 내역 
위의 문제 방지
- 동작 
- 특이 사항
close: #268
=> [Update] 회원가입 / 프로필 수정 페이지 글자수 제한 추가 및 splash 경로 변경

css/userList.css, js/follow.js
- 이유
- 쿼리스트링에 limit 추가
css속성 변경
- ![image](https://user-images.githubusercontent.com/76831344/181007576-f8a06ed0-6f4e-4e84-be6d-c3501cb82775.png)
- 특이 사항
close: #277
=> [Fix] 팔로우,팔로워 limit, css 수정

css/feed.css, js/profile-post.js
resolves: #275 
- 앨범뷰 버튼 클릭하여 게시글 누를 때 똑같은 게시글만 보여짐
- 데이터 아이디값 변경 
- 특이 사항
close: #275
=> [Fix] 앨범뷰 버튼 클릭시 같은 게시글만 보이는 현상 수정

js/common.js, js/editprofile.js, js/join.js
vercel을 이용한 배포 후 기본 이미지가 출력되지 않는 이슈
resolves: #273
url 조건부 할당으로 변경
입력된 이미지 값이 없을 때 절대 경로의 이미지로 할당
- 이유
배포 후 발생하는 에러 해결
- 작업 내역 
- 동작 
- 특이 사항
close: #273
배포 페이지의 기본 이미지가 출력 여부
=> [Fix] vercel을 이용한 배포 후 기본 이미지가 출력되지 않는 이슈 해결 시도

css/profile.css, js/profile-product.js, pages/profile.html
- 상품 확인 모달에서 구매로 이어지기 위해 채팅창으로 연결해주는 기능이 필요하다는 의견이 나와 수정
- 상품 확인 모달에서 채팅하기 버튼을 추가해 채팅창으로 넘어가게한다.
- ![chrome-capture-2022-6-26](https://user-images.githubusercontent.com/76831344/181036640-255a255b-bb79-40fb-a42e-b53183029d67.gif)
- 특이 사항
close: #279
=> [Add] profile-product 상품 확인모달 채팅버튼 추가

js/common.js, js/editprofile.js, js/join.js
url 문제로 인한 문제 해결
resolves: #285
전체적인 url 변경
- 이유
문제 발생
- 작업 내역 
- 동작 
정상 동작
- 특이 사항
close: #285
=> [Fix] url 문제로 인한 문제 해결

css/postcomment.css
Resolve: #287 
- 좋아요 버튼 클릭 시 아이콘 이동되는 현상
- css 수정
- 동작 
- 특이 사항
close: #287
=> postcomment.css 수정

js/profile.js
- 채팅 버튼 선택 시 추가 기능이 필요
- 버튼 클릭 시 href를 chatroom으로 이동
- 
- 특이 사항
close: #290
=> [Add] profile 페이지 채팅버튼 선택 시 이동

css/feed.css
Resolves: #291 
- 폰트사이즈 수정 필요
- 게시글 부분 폰트 사이즈 변경
- 동작 
- 특이 사항
close: #291
=> [Update] feed.css 폰트 사이즈 수정

css/postcomment.css
css 수정
resolves: #295
- 이유
css 변경
- 작업 내역 
css 변경
- 동작 
- 특이 사항
close: #295
=> [Fix] postcomment.css 수정

css/userList.css, js/follow.js
- 팔로워, 팔로잉 쿼리스트링 limit 개수 제한두지 않게하기, css깨짐 수정
- follow 페이지 쿼리스트링 infinity로 변경, css 수정
- 
- 특이 사항
close: #297
=> [Fix] follow 페이지 쿼리스트링, css 수정

css/feed.css, css/home.css, css/postcomment.css
- home, feed, postcomment css 변경 필요
- home, feed, postcomment css 변경 
- 특이 사항
close: #
=> [update]home,feed,postcomment css update

css/chat.css, css/chatroom.css, css/feed.css, css/imageRegister.css, css/post.css, css/postcomment.css, css/reset.css, html/imageRegister.html, js/common.js, js/editProduct.js, js/editpost.js, js/editprofile.js, js/login.js, js/post.js, js/postcomment.js, js/product.js, js/profile-post.js, js/profile-product.js, js/profile.js, pages/chat.html, pages/chatroom.html, pages/editpost.html, pages/post.html, pages/postcomment.html, pages/profile.html
Resolves: #306 
- [] 기능 수정 :
- 전체 파일 주석 제거
- html, css, js 파일 주석 제거
- 특이 사항
close: #306
=> [Rename] 전체 파일 주석 정리

css/postcomment.css, js/common.js, js/home.js, js/postcomment.js, js/search.js, pages/home.html
resolves: #312 
- 이미지 에러 처리 함수 추가
- 홈화면 common.js 클릭 이벤트 에러 예외처리
- 이미지 에러 처리 함수 추가
- 홈화면 common.js 클릭 이벤트 에러 예외처리
- 동작 
- 특이 사항
close: #312
=> [Fix] common.js 이미지 엑박 처리 함수 추가, 홈화면 common.js 클릭 이벤트 에러 예외처리

.vscode/settings.json
- 이유
- 작업 내역 
- 동작 
- 특이 사항
close: #
=> [update]vscode 수정

js/home.js, js/postcomment.js
이미지 엑박 수정
resolves: #317
- 이유
이미지 엑박 수정
- 작업 내역 
이미지 엑박 수정
- 동작 
- 특이 사항
close: #317
=> [Fix] 이미지 엑박 수정

js/common.js, js/profile-post.js, js/profile-product.js, js/profile.js
- 이유
- 
common js 이미지 에러 처리 함수 옵셔널 체이닝 추가
profile 관련 페이지들 이미지 에러 처리 
- 동작 
- 특이 사항
close: #319
=> [Update] profile 페이지들 이미지 에러 처리, common js 이미지 에러처리 옵셔널체이닝 추가

js/search.js, pages/search-result.html
- 검색창 js, html 수정
- 검색창 js, html 수정
- 동작 
- 특이 사항
close: #
=> [Update] 검색창 js, html 수정

js/login.js, js/splash.js
splash, login 페이지 토큰 검증 기능 추가
resolves: #309
splash와 login 페이지에 토큰 검증 기능 추가
- 이유
유효하지 않는 토큰으로 로그인 방지
- 작업 내역 
사용자의 토큰을 검증하는 API 추가
- 동작 
토큰을 조회하여 올바른 토큰이라면 스플래쉬 페이지와 로그인 페이지에서 홈 페이지로 바로 이동
만약 올바르지 않은 토큰이라면 스플래쉬 페이지에서 인트로 페이지로 이동한다.
- 특이 사항
close: #309
=> [Update] splash, login 페이지 토큰 검증 기능 추가

css/editprofile.css, css/input.css, css/join.css, pages/editprofile.html, pages/join.html, pages/login.html
input 자동 완성 기능 비활성화 및 모바일 스타일 변경(iOS input 스타일)
resolves: #323
input 태그 자동 완성 속성 비활성화 / 모바일 구동 시 iOS 스타일 변경
- 이유
input 태그 자동 완성으로 input 태그가 가려짐 개선
모바일 구동 시 웹과 동일한 스타일을 가지기 위함
input 태그의 autocomplete 속성 비활성
iOS 모바일 구동 시 border-radius와 shadow가 적용된 부분 수정
- 작업 내역 
- 동작 
- 특이 사항
모바일 구동 시 확인 요망
close: #323
=> [Update] input 자동 완성 기능 비활성화 및 모바일 스타일 변경(iOS input 스타일)

js/login.js
토큰 검증 기능과 계정 검증 기능 충돌로 일부 코드 수정
resolves: #326
일부 코드 변경
- 이유
아이디와 비밀번호가 일치하지 않을 때 에러메세지 미출력 및 토큰 검증만 실행하는 오류 수정
- 작업 내역 
- 동작 
- 특이 사항
close: #326 
에러메세지 출력 여부 확인
=> [Fix] 토큰 검증 기능과 계정 검증 기능 충돌로 일부 코드 수정

html/feed.html, html/modal-chat.html, html/modal-comment-delete.html, html/modal-comment-report.html, html/modal-post.html, html/modal-product.html, html/modal-profile.html, html/tab-menu.html, pages/home.html, pages/search-result.html
Resolves: #325 
- 사용 언어 통일 필요
- html 파일 언어 'ko'로 통일
- 동작 
- 특이 사항
close: #325
=> [Update] <html lang=ko> 로 통일

css/feed.css, css/postcomment.css, css/search-result.css
resolves: #329 
- 검색결과 아이디가 길면 화면을 넘어가는 현상 발생
- css 수정하여 말줄임으로 처리함 
- 특이 사항
close: #329
=> [Fix] 검색창 아이디 넘침 현상 수정

.vscode/settings.json, css/profile.css
- 이유
- font-size가 지정되어있지 않아서 14px로 지정
- 
- 특이 사항
close: #331
=> [Design] profile 상품 확인 모달 채팅하기버튼 수정

css/chatroom.css, css/feed.css, css/postcomment.css, css/search-result.css, js/postcomment.js, js/profile-post.js, pages/chatroom.html
resolves: #333 
- 채팅창 UI 깨짐 현상, 
- 프로필이미지 커서 변경, 
- 프로필페이지 모달 수정
- 채팅창 UI 깨짐 현상, 
- 프로필이미지 커서 변경, 
- 프로필페이지 모달 수정
- 특이 사항
close: #333
=> [Update] 채팅창 UI 깨짐 현상, 프로필이미지 커서 변경, 프로필페이지 모달 수정

js/common.js, js/editprofile.js
resolves: #338
- 이유
- url 변수 삼항 연산자 처리, editProfile 이미지 에러처리 함수 적용
- 동작 
- 특이 사항
close: #338
=> [Fix] common.js url 변경, editProfile 이미지 에러처리

css/postcomment.css
resolves: #340 
- 댓글 상세페이지에서 이미지 없는 게시글 ui 깨짐
- Postcomment.css 파일 수정
- 특이 사항
close: #340
=> [Update] postcomment.css 수정

README.md, js/common.js, js/editprofile.js, js/follow.js, js/home.js, js/join.js, js/login.js, js/postcomment.js, js/profile.js, js/search.js, js/splash.js
- 이유
기존 api url의 변경
- 작업 내역 
모든 .js 파일 내 fetch를 위한 api url의 값을 변경
- 동작 
1. api url의 교체로 정상동작한다.
2. 기존 api url로 적용되어 있어 대체 텍스트가 출력되던 이미지가 정상적으로 로드된다.
- 특이 사항
close: 없음
=> [Fix] 기존 api url 변경으로 api 변경
